spring:
  config:
    import: optional:file:../.env[.properties]
  main:
    allow-bean-definition-overriding: true
  application:
    name: construction-platform

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:construction_management}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: HikariPool-ConstructionPlatform

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.xml
    enabled: ${LIQUIBASE_ENABLED:true}

server:
  port: ${APP_PORT:8080}

schedule:
  # Danh sách ngày lễ được loại trừ khỏi thời lượng dự án.
  # Các giá trị có thể được đặt theo định dạng: YYYY-MM-DD,YYYY-MM-DD.
  holidays: ""

logging:
  level:
    root: INFO
    com.ntdhtcct: DEBUG
    liquibase: INFO
    org.springframework.jdbc: DEBUG
